PUT http://localhost:8080/api/productos/63321cf831862ade168a2773 HTTP/1.1
content-type: application/json

{
    "precio": 0,
    "nombre": "asdasdfasd",
    "codigo": "12312412",
    "precio": 156464,
    "stock": 1,
    "thumbnail":"asd",
    "__v": 0
}